# Generated by Django 4.1.5 on 2023-01-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='titel',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
